### ISSUE TITLE
[Meta] Refactor `lib\install.ps1`

### ISSUE THREAD

**Issue by Ash258** [lukesampson/scoop#3149]
This should be done when https://github.com/scoopinstaller/install is ready, so we do not have to care about moving something needed for scoop installation

1. [ ] Slim whole script
    1. **Functions moving**
        - There is no need to have every download / check function inside install module.
        - Install module should contain only install related functions
        1. [ ] `nightly_version` -> lib\versions.ps1
        1. [ ] Download related functions -> lib\download.ps1
            - `dl_with_cache`
            - `do_dl`
            - `dl`
            - `dl_progress_output`
            - `dl_progress`
            - `dl_urls`
        1. [ ] Aria2 related functions -> lib\aria2.ps1
            - `aria_exit_code`
            - `get_filename_from_metalink`
            - `dl_with_cache_aria2`
        1. [ ] Environment related functions -> lib\environment.ps1
            - `env_add_path`
            - `add_first_in_path`
            - `env_rm_path`
            - `env_set`
            - `env_rm`
        1. [ ] Persist related functions -> lib\persist.ps1
            - `persist_def`
            - `persist_data`
            - `unlink_persist_data`
            - `persist_permission`
        1. [x] Extraction related functions -> lib\decompress.ps1 (#3169)
            - `unpack_inno`
            - `extract_msi`
            - `extract_lessmsi`
    1. **Adopt Verb-Noun naming of functions**
1. [ ] Downloading refactor / unify
    1. [ ] Download URl should strip scoop renames `#/whaterever` as it could potentially cause problems
    1. [ ] All `dl_with_cache functions` should have same parameter list
    1. [ ] There is incosistency between `dl_with_cache` normal and aria2 version
        - Aria2 version is capable of checking hashes
        - Aria2 version is removing cached file with $use_cache set to $false
        1. [ ] Create new function `Initialize-Download ([String[]] $Url, [Switch] $UseCache, [Switch] $CheckHash)`
            - This function will be only wraper, which will look like this:

                ```powershell
                $paramsSplat = @{usecache, ...}
                if (aria2-enabled) { dl_witch_cache_aria2 @paramsSplat }
                elseif (curl-enabled) { dl_witch_cache_curl @paramsSplat } # Easier to maintain new download managers
                else { dl_witch_cache @paramsSplat }
                ```

            - This will save some lines, where you check for aria2 enabled in updates, install etc, ...
                - No need to manually check inside other code fractions. (as in #3148)
                - You just call `Scoop-Download` and not care for anything
            - This wrapper will be called for dowloading instead of `dl`
            - Also it will allow binaries to use prefered manager without touching binary for each new download manager with some `if`
1. [ ] `install_app` function refactor
    - This should be enough to change <https://github.com/lukesampson/scoop/blob/26d694e46dc973d97f404545f8627770daf4b35f/lib/install.ps1#L43> to 2 lines
        - Download (It could return $fname)
        - Extract if applicable
1. [ ] Adopt new download function in whole codebase (binaries, etc..)
